server:
  port: 8082

spring:
  application:
    name: frontend-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  mvc:
    cache: false
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/,classpath:/public/


logging:
  level:
    org.springframework: INFO









